apiVersion: v1
kind: LimitRange
metadata:
  name: my-limitrange
spec:
  limits:
    - default:
        cpu: 700m
        memory: 900Mi
      defaultRequest:
        cpu: 110m
        memory: 111Mi
      max:
        cpu: 800m
        memory: 1Gi
      min:
        cpu: 100m
        memory: 99Mi
      type: Container