{{- if .Values.prometheus.servicemonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "pint.fullname" . }}
  {{- with .Values.prometheus.servicemonitor.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.prometheus.servicemonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "pint.labels" . | nindent 6 }}
  endpoints:
  - targetPort: 8080
    path: "/metrics"
    interval: {{ .Values.prometheus.servicemonitor.interval }}
{{- end }}
