apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: persistent-volume
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/dkdr/k8s12.git
    targetRevision: HEAD
    path: k8s/persistent_storage
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: storagetest

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10